//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.30 at 01:05:45 PM PDT 
//


package com.telus.workforcemgmt.dto.assignmentmanagement;

import lombok.Data;

@Data
public class ComponentLocation { 

    private String unitTypeCd;
    private String unitName;
    private String floorTypeCd;
    private String floorName;
    private String buildingTypeCd;
    private String buildingName;

  
}
