//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.30 at 01:05:45 PM PDT 
//


package com.telus.workforcemgmt.dto.assignmentmanagement;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NonNull;

@Data
@Builder(toBuilder = true) 
@AllArgsConstructor
public class TypeCode {

	@NonNull private String typeCd;
    private String descriptionTxt;
    
        
}
